#!/bin/sh

echo "=================================================="
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo "======== Proxy dependencies ========"
echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
echo ""
echo ">>>>> Install python and python3..."
brew install python python3
echo ">>>>> Install PyOpenSSL for python..."
sudo easy_install PyOpenSSL
echo ">>>>> Install PyCrypto for python..."
sudo easy_install PyCrypto

#Not using cow for a long time.
#command -v cow >/dev/null 2>/dev/null || (
#    echo ">>>>> Install cow via curl..."
#    [ ! -d "${HOME}/local/cow" ] && mkdir -pv "${HOME}/local/cow"
#    pushd "${HOME}/local/cow" && (
#        curl -L git.io/cow | bash
#        popd
#    )
#    echo ">>>>> Done!"
#)
